// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package querytest

import (
	"context"

	"cloud.google.com/go/spanner"
	"errors"
	"google.golang.org/api/iterator"
)

const placeholder = `-- name: Placeholder :exec
SELECT 1
`

func (q *Queries) Placeholder(ctx context.Context) error {
	stmt := spanner.NewStatement(placeholder)
	iter := q.db.Query(ctx, stmt)
	defer iter.Stop()
	for {
		_, err := iter.Next()
		if errors.Is(err, iterator.Done) {
			break
		} else if err != nil {
			return err
		}
	}

	return nil
}
